name: Fetch & Process Latest YouTube Video

# run every hour (you can tweak the cron)
on:
  schedule:
    - cron:  '0 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ Check out your code
      - uses: actions/checkout@v4

      # 2️⃣ Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # 3️⃣ Install your requirements
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4️⃣ Run the chain:
      #    first get latest ID, then process it
      - name: Fetch & Process
        run: |
          # get the latest video ID
          VIDEO_ID=$(python manage.py latest_video --quiet)
          echo "Latest video: $VIDEO_ID"
          # now run your processing command
          python manage.py process_video --video-id "$VIDEO_ID"
        env:
          WEB_APP_URL: ${{ secrets.WEB_APP_URL }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          VIDEO_URL: ${{ secrets.VIDEO_URL }}
          # add any other env vars you need here
