name: YouTube Video Checker

on:
  push:
    branches: [main]   # Runs when changes are pushed to main branch.
  schedule:
    # Runs every 4 hours (UTC time)
    - cron: '0 */4 * * *'
  workflow_dispatch:  # Allow manual triggering

jobs:
  check-videos:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
      
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set environment variables
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        G_SCRIPT_URL: ${{ secrets.G_SCRIPT_URL }}
        WEB_APP_URL: ${{ secrets.WEB_APP_URL }}
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        YT_COOKIES: ${{ secrets.YT_COOKIES }}
      run: |
        echo "DJANGO_SETTINGS_MODULE=youtube_automation.settings" >> $GITHUB_ENV
        echo "SLACK_BOT_TOKEN=$SLACK_BOT_TOKEN" >> $GITHUB_ENV
        echo "G_SCRIPT_URL=$G_SCRIPT_URL" >> $GITHUB_ENV
        echo "WEB_APP_URL=$WEB_APP_URL" >> $GITHUB_ENV
        echo "GEMINI_API_KEY=$GEMINI_API_KEY" >> $GITHUB_ENV
        echo "${{ secrets.YT_COOKIES }}" | base64 --decode > cookies.txt
        cat cookies.txt | head -n 1 # Verify first line (don't show full content)
        
    - name: Run video checker
      run: |
        # Verify original cookies file
        echo "Original cookies file:"
        ls -la cookies.txt
        
        # Create properly formatted enhanced cookies file
        echo "Creating properly formatted cookies file..."
        {
          echo "# Netscape HTTP Cookie File"
          echo "# This is a generated file. Do not edit."
          echo ""
          echo -e ".youtube.com\tTRUE\t/\tTRUE\t1800000000\tCONSENT\tYES+cb.20230101.00-00-00"
          cat cookies.txt | grep -v '^#'  # Remove existing comments to avoid duplication
        } > enhanced_cookies.txt
        
        # Verify enhanced cookies
        echo "Enhanced cookies file contents (first 5 lines):"
        head -n 5 enhanced_cookies.txt
        
        # Download with enhanced cookies
        echo "Downloading YouTube video..."
        yt-dlp \
          --cookies enhanced_cookies.txt \
          --verbose \
          --force-ipv4 \
          --sleep-interval 5 \
          --max-sleep-interval 10 \
          --user-agent "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36" \
          https://www.youtube.com/watch?v=InuRAWhZ15Y
        
        # Clean up
        rm -f cookies.txt enhanced_cookies.txt
        
        # Run Django command
        python manage.py new_video_notification_in_slack