name: YouTube Video Checker

on:
  push:
    branches: [main]   # Runs when changes are pushed to main branch.
  schedule:
    # Runs every 4 hours (UTC time)
    - cron: '0 */4 * * *'
  workflow_dispatch:  # Allow manual triggering

jobs:
  check-videos:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
      
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set environment variables
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        G_SCRIPT_URL: ${{ secrets.G_SCRIPT_URL }}
        WEB_APP_URL: ${{ secrets.WEB_APP_URL }}
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        YT_COOKIES: ${{ secrets.YT_COOKIES }}
      run: |
        echo "DJANGO_SETTINGS_MODULE=youtube_automation.settings" >> $GITHUB_ENV
        echo "SLACK_BOT_TOKEN=$SLACK_BOT_TOKEN" >> $GITHUB_ENV
        echo "G_SCRIPT_URL=$G_SCRIPT_URL" >> $GITHUB_ENV
        echo "WEB_APP_URL=$WEB_APP_URL" >> $GITHUB_ENV
        echo "GEMINI_API_KEY=$GEMINI_API_KEY" >> $GITHUB_ENV
        echo "${{ secrets.YT_COOKIES }}" | base64 --decode > cookies.txt
        cat cookies.txt | head -n 1 # Verify first line (don't show full content)
        
    - name: Run video checker
      run: |
        # 1. Install latest tools
        pip install --upgrade yt-dlp
    
        # 2. Create hybrid authentication approach
        {
          echo "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
          echo "Referer: https://www.youtube.com/"
          echo "Cookie: $(grep -E 'LOGIN_INFO' cookies.txt | awk -F'\t' '{print $6 \"=\" $7}'); CONSENT=YES+cb.20230101.00-00-00"
        } > youtube_headers.txt
    
        # 3. Run with multiple bypass techniques
        yt-dlp \
          --sleep-interval 15 \
          --max-sleep-interval 30 \
          --force-ipv4 \
          --no-check-certificates \
          --limit-rate 500K \
          --verbose \
          --add-header @youtube_headers.txt \
          --extractor-args youtube:player_client=android \
          --geo-bypass \
          --proxy "https://" \
          https://www.youtube.com/watch?v=InuRAWhZ15Y
    
        # 4. Clean up
        rm -f cookies.txt youtube_headers.txt
        python manage.py new_video_notification_in_slack